### ISSUE TITLE
农历的年份是不是有些是错的

### ISSUE THREAD

**Issue by bbu4u** [hungtcs/traditional-chinese-calendar-database#23]
比如1902年2月5日应该是辛丑年  而数据表里面是壬寅年

**Comment by hungtcs** [comment]
@huoxiongmao 以 [database/origin](https://github.com/hungtcs/traditional-chinese-calendar-database/tree/master/database/origin) 中的文件为准，1902年2月5日是 [立春](https://jieqi.bmcx.com/1902_lichun__jieqi/) 

https://wannianrili.bmcx.com/1902-02-05__wannianrili/

![image](https://user-images.githubusercontent.com/11692935/182060910-f8955786-238c-435c-93f5-a9268cd00d0e.png)

**Comment by bbu4u** [comment]
他这个数据是错的，你看2月5日还没过年了就是牛年，过年了你看看大年初一（2月8日）的数据还是牛年。

**Comment by hungtcs** [comment]
@huoxiongmao 属相的交替和干支是以立春为准的，不是以春节为准。

- https://www.zhihu.com/question/22318210

**Comment by hungtcs** [comment]
@huoxiongmao 你可以从 [database/origin](https://github.com/hungtcs/traditional-chinese-calendar-database/tree/master/database/origin) 重新进行转换一下
